// SPDX-License-Identifier: GPL-3.0-or-later

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let tests_dir = manifest_dir.join("tests");
    let widget_dir = tests_dir.join("widget");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let registry_path = out_dir.join("widget_test_registry.rs");

    println!(
        "cargo:rerun-if-changed={}",
        tests_dir.join("widget.rs").display()
    );
    println!("cargo:rerun-if-changed={}", widget_dir.display());

    let mut files: Vec<PathBuf> = fs::read_dir(&widget_dir)
        .expect("read widget test dir")
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .collect();
    files.sort();

    let common_path = files
        .iter()
        .find(|path| file_stem(path) == "common")
        .expect("widget/common.rs exists")
        .clone();

    let mut generated = String::new();
    generated.push_str("// @generated by crates/lushtext/build.rs\n");
    generated.push_str(&format!(
        "#[path = r#\"{}\"#]\nmod common;\n",
        common_path.display()
    ));

    let mut module_names = Vec::new();
    for path in files {
        let module_name = file_stem(&path);
        if module_name == "common" {
            continue;
        }
        module_names.push(module_name.clone());
        let source = fs::read_to_string(&path).expect("read widget test source");
        let tests = extract_test_functions(&source);
        let transformed_path = out_dir.join(format!("widget_mod_{module_name}.rs"));
        fs::write(&transformed_path, transform_test_source(&source))
            .expect("write transformed widget test source");
        generated.push_str(&format!(
            "#[path = r#\"{}\"#]\nmod {module_name};\nmod __register_{module_name} {{\n    pub fn register(tests: &mut Vec<(&'static str, fn())>) {{\n",
            transformed_path.display()
        ));
        for test_name in tests {
            generated.push_str(&format!(
                "        tests.push((\"{module_name}::{test_name}\", super::{module_name}::{test_name}));\n"
            ));
        }
        generated.push_str("    }\n}\n");
    }

    generated.push_str("pub fn all_widget_tests() -> Vec<(&'static str, fn())> {\n");
    generated.push_str("    let mut tests = Vec::new();\n");
    for module_name in module_names {
        generated.push_str(&format!(
            "    __register_{module_name}::register(&mut tests);\n"
        ));
    }
    generated.push_str("    tests\n}\n");

    fs::write(registry_path, generated).expect("write widget registry");
}

fn file_stem(path: &Path) -> String {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .expect("utf-8 file stem")
        .to_string()
}

fn extract_test_functions(source: &str) -> Vec<String> {
    let lines: Vec<&str> = source.lines().collect();
    let mut tests = Vec::new();

    for (idx, line) in lines.iter().enumerate() {
        if line.trim() != "#[test]" {
            continue;
        }

        let Some(fn_line) = lines[idx + 1..]
            .iter()
            .map(|line| line.trim())
            .find(|line| line.starts_with("fn "))
        else {
            continue;
        };

        let Some(name) = fn_line
            .strip_prefix("fn ")
            .and_then(|line| line.split('(').next())
        else {
            continue;
        };

        tests.push(name.to_string());
    }

    tests
}

fn transform_test_source(source: &str) -> String {
    let mut transformed = String::new();

    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed == "#[test]" {
            continue;
        }

        if let Some(rest) = line.trim_start().strip_prefix("fn test_") {
            let indent_len = line.len() - line.trim_start().len();
            let indent = &line[..indent_len];
            transformed.push_str(indent);
            transformed.push_str("pub fn test_");
            transformed.push_str(rest);
            transformed.push('\n');
            continue;
        }

        transformed.push_str(line);
        transformed.push('\n');
    }

    transformed
}
