// SPDX-License-Identifier: GPL-3.0-or-later

//! Checked action catalog for automation, documentation, and drift audits.
//!
//! This service layer keeps catalog construction GTK-free while comparing the
//! pure catalog against command registries, visible action strings, and D-Bus
//! introspection snapshots supplied by UI or smoke adapters.

use std::collections::{BTreeMap, BTreeSet};

use crate::model::action_catalog::{
    ActionCatalogEntry, ActionCoverageLane, ActionExposure, ActionReferenceRow, ActionScope,
    ActionSurface, ActionValueType, ExternalActivationSafety, ObservedAction,
};
use crate::services::palette;

#[cfg(test)]
mod tests;

/// Result type used by catalog checks that may report several drift findings.
pub type AuditResult = Result<(), Vec<ActionCatalogAuditFailure>>;

/// One actionable catalog drift finding.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ActionCatalogAuditFailure {
    DuplicateActionIds(Vec<String>),
    MissingDocsAnchors(Vec<String>),
    MissingCoverage(Vec<String>),
    MissingCatalogEntries {
        source: &'static str,
        action_ids: Vec<String>,
    },
    MissingRegisteredActions {
        scope: ActionScope,
        action_ids: Vec<String>,
    },
    TypeMismatches(Vec<ActionSignatureMismatch>),
}

/// Expected-versus-observed type mismatch for one exported action.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ActionSignatureMismatch {
    pub action_id: String,
    pub expected_parameter: ActionValueType,
    pub observed_parameter: ActionValueType,
    pub expected_state: ActionValueType,
    pub observed_state: ActionValueType,
}

/// Return the complete catalog for the current implementation baseline.
#[must_use]
pub fn entries() -> &'static [ActionCatalogEntry] {
    ACTION_CATALOG
}

/// Generate the serializable artifact consumed by developer automation docs.
#[must_use]
pub fn developer_reference_rows() -> Vec<ActionReferenceRow> {
    ACTION_CATALOG
        .iter()
        .map(ActionReferenceRow::from)
        .collect()
}

/// Generate pretty JSON for docs tooling without hand-copying catalog fields.
///
/// # Errors
///
/// Returns a serialization error if the catalog contains a value that serde
/// cannot encode. The current catalog is static and should not fail.
pub fn developer_reference_json() -> serde_json::Result<String> {
    serde_json::to_string_pretty(&developer_reference_rows())
}

/// Check catalog-only invariants before comparing against external surfaces.
///
/// # Errors
///
/// Returns every catalog invariant violation found, such as duplicate action
/// IDs, missing documentation anchors, or rows without coverage lanes.
pub fn audit_catalog(entries: &[ActionCatalogEntry]) -> AuditResult {
    let mut failures = Vec::new();
    let mut seen = BTreeSet::new();
    let mut duplicates = BTreeSet::new();
    let mut missing_docs = Vec::new();
    let mut missing_coverage = Vec::new();

    for entry in entries {
        let action_id = entry.qualified_id();
        if !seen.insert(action_id.clone()) {
            duplicates.insert(action_id.clone());
        }
        if entry.docs_anchor.trim().is_empty() {
            missing_docs.push(action_id.clone());
        }
        if entry.coverage_lanes.is_empty() {
            missing_coverage.push(action_id);
        }
    }

    if !duplicates.is_empty() {
        failures.push(ActionCatalogAuditFailure::DuplicateActionIds(
            duplicates.into_iter().collect(),
        ));
    }
    if !missing_docs.is_empty() {
        failures.push(ActionCatalogAuditFailure::MissingDocsAnchors(missing_docs));
    }
    if !missing_coverage.is_empty() {
        failures.push(ActionCatalogAuditFailure::MissingCoverage(missing_coverage));
    }

    finish_audit(failures)
}

/// Compare observed app/window action signatures against exported catalog rows.
///
/// # Errors
///
/// Returns drift findings when exported actions are missing from the catalog,
/// cataloged exports are not registered, or observed parameter/state types no
/// longer match their catalog rows.
pub fn audit_observed_actions(scope: ActionScope, observed: &[ObservedAction<'_>]) -> AuditResult {
    let expected = exported_entries_by_name(scope);
    let observed_by_name: BTreeMap<&str, &ObservedAction> = observed
        .iter()
        .filter(|action| action.scope == scope)
        .map(|action| (action.name.as_ref(), action))
        .collect();

    let mut failures = Vec::new();
    let mut missing_catalog = Vec::new();
    let mut missing_registered = Vec::new();
    let mut mismatches = Vec::new();

    for observed_action in observed_by_name.values() {
        let Some(expected_entry) = expected.get(observed_action.name.as_ref()) else {
            missing_catalog.push(observed_action.qualified_id());
            continue;
        };
        if expected_entry.parameter_type != observed_action.parameter_type
            || expected_entry.state_type != observed_action.state_type
        {
            mismatches.push(ActionSignatureMismatch {
                action_id: observed_action.qualified_id(),
                expected_parameter: expected_entry.parameter_type,
                observed_parameter: observed_action.parameter_type,
                expected_state: expected_entry.state_type,
                observed_state: observed_action.state_type,
            });
        }
    }

    for expected_name in expected.keys() {
        if !observed_by_name.contains_key(expected_name) {
            missing_registered.push(scope.qualified_id(expected_name));
        }
    }

    if !missing_catalog.is_empty() {
        failures.push(ActionCatalogAuditFailure::MissingCatalogEntries {
            source: "registered-actions",
            action_ids: missing_catalog,
        });
    }
    if !missing_registered.is_empty() {
        failures.push(ActionCatalogAuditFailure::MissingRegisteredActions {
            scope,
            action_ids: missing_registered,
        });
    }
    if !mismatches.is_empty() {
        failures.push(ActionCatalogAuditFailure::TypeMismatches(mismatches));
    }

    finish_audit(failures)
}

/// Check command-palette command IDs against the shared catalog.
///
/// # Errors
///
/// Returns missing-catalog findings when a command-palette entry references an
/// action ID that is not represented in the shared catalog.
pub fn audit_command_palette_actions() -> AuditResult {
    audit_cataloged_ids(
        "command-palette",
        palette::all_commands().iter().map(|command| command.id),
    )
}

/// Check statically discoverable menu, shortcut, toolbar, and context actions.
///
/// # Errors
///
/// Returns missing-catalog findings when a statically discoverable menu,
/// shortcut, toolbar, or context-menu action has no shared catalog row.
pub fn audit_visible_static_actions() -> AuditResult {
    audit_cataloged_ids(
        "visible-static-actions",
        STATIC_VISIBLE_ACTION_IDS.iter().copied(),
    )
}

fn audit_cataloged_ids(
    source: &'static str,
    ids: impl IntoIterator<Item = &'static str>,
) -> AuditResult {
    let cataloged: BTreeSet<String> = ACTION_CATALOG
        .iter()
        .map(ActionCatalogEntry::qualified_id)
        .collect();
    let mut missing = BTreeSet::new();

    for id in ids {
        if !cataloged.contains(id) {
            missing.insert(id.to_string());
        }
    }

    if missing.is_empty() {
        Ok(())
    } else {
        Err(vec![ActionCatalogAuditFailure::MissingCatalogEntries {
            source,
            action_ids: missing.into_iter().collect(),
        }])
    }
}

fn exported_entries_by_name(
    scope: ActionScope,
) -> BTreeMap<&'static str, &'static ActionCatalogEntry> {
    ACTION_CATALOG
        .iter()
        .filter(|entry| entry.scope == scope && entry.exposure == ActionExposure::Exported)
        .map(|entry| (entry.name, entry))
        .collect()
}

fn finish_audit(failures: Vec<ActionCatalogAuditFailure>) -> AuditResult {
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures)
    }
}

const ACTION_CATALOG: &[ActionCatalogEntry] = &[
    ActionCatalogEntry::new(
        ActionScope::App,
        "preferences",
        "Preferences",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active window.",
        "app",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-app-preferences",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::App,
        "quit",
        "Quit",
        ActionValueType::None,
        ActionValueType::None,
        "Always registered; close flows still own save/modified safety.",
        "app",
        &[ActionSurface::CommandPalette, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-app-quit",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::App,
        "about",
        "About LushText",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active window.",
        "app",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-app-about",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "new-tab",
        "New File",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled.",
        "window/actions",
        &[
            ActionSurface::HeaderButton,
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-new-tab",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "open-file",
        "Open File",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; opens the normal file dialog.",
        "window/actions",
        &[
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::CustomMenuWidget,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-open-file",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "open-recent",
        "Open Recent Documents",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; opens the recent-document Open popover and focuses search.",
        "window/recent_open",
        &[
            ActionSurface::HeaderButton,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-open-recent",
        &[
            ActionCoverageLane::Unit,
            ActionCoverageLane::Widget,
            ActionCoverageLane::AccessibilitySmoke,
            ActionCoverageLane::VisualSmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-open-popover-query",
        "Set Open Popover Query",
        ActionValueType::String,
        ActionValueType::None,
        "Requires the visible recent-document Open popover.",
        "window/recent_open",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-open-popover-query",
        &[
            ActionCoverageLane::Unit,
            ActionCoverageLane::Widget,
            ActionCoverageLane::AccessibilitySmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "open-folder",
        "Open Folder",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; opens the normal workspace folder flow.",
        "window/actions",
        &[ActionSurface::CommandPalette, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-open-folder",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "save",
        "Save",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab.",
        "window/actions",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-save",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "save-as",
        "Save As",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab.",
        "window/actions",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-save-as",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-local-history",
        "Local History",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document with local-history browsing available.",
        "window/local_history",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::EditorContextMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-show-local-history",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-encoding-controls",
        "Text Encoding",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active document when the status-bar control is useful.",
        "window/encoding",
        &[ActionSurface::StatusBar, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-show-encoding-controls",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-line-ending-controls",
        "Line Endings",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active document when the status-bar control is useful.",
        "window/encoding",
        &[ActionSurface::StatusBar, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-show-line-ending-controls",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-file-health",
        "File Health",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active document with inspectable file-health state.",
        "window/encoding",
        &[ActionSurface::PropertiesPanel, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-show-file-health",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "cycle-invisible-characters",
        "Cycle Invisible Characters",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab.",
        "window/actions",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-cycle-invisible-characters",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "begin-search",
        "Find and Replace",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab.",
        "window/actions",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-begin-search",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-search-query",
        "Set In-Document Search Query",
        ActionValueType::String,
        ActionValueType::None,
        "Requires an active tab.",
        "window/actions",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-search-query",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "begin-replace",
        "Begin Replace",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab.",
        "window/actions",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-begin-replace",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "next-match",
        "Next In-Document Match",
        ActionValueType::None,
        ActionValueType::None,
        "Requires the in-document search UI to be visible.",
        "window/actions",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-next-match",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "prev-match",
        "Previous In-Document Match",
        ActionValueType::None,
        ActionValueType::None,
        "Requires the in-document search UI to be visible.",
        "window/actions",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-prev-match",
        &[ActionCoverageLane::Unit],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "close-tab",
        "Close Tab",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab; normal close safety still applies.",
        "window/actions",
        &[
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-close-tab",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "select-tab",
        "Select Tab",
        ActionValueType::U32,
        ActionValueType::None,
        "Requires an active tab; out-of-range indices leave the active tab unchanged.",
        "window/actions",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-select-tab",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-command-palette",
        "Command Palette",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled.",
        "window/focus_indexing",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-command-palette",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-command-palette-query",
        "Set Command Palette Query",
        ActionValueType::String,
        ActionValueType::None,
        "Requires a visible command palette.",
        "window/focus_indexing",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-command-palette-query",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-command-palette-mode",
        "Set Command Palette Mode",
        ActionValueType::String,
        ActionValueType::None,
        "Requires a visible command palette; accepts all, files, notes, or commands.",
        "window/focus_indexing",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-command-palette-mode",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-search-panel",
        "Workspace Search",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; the panel owns empty/no-workspace states.",
        "window/search",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-search-panel",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-search-panel-visible",
        "Set Workspace Search Visibility",
        ActionValueType::Bool,
        ActionValueType::None,
        "Always enabled; follows the same focus and transition path as the workspace search toggle.",
        "window/actions",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-set-search-panel-visible",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-search-panel-query",
        "Set Workspace Search Query",
        ActionValueType::String,
        ActionValueType::None,
        "Requires a visible workspace search panel.",
        "window/search",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-search-panel-query",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-search-panel-replace-query",
        "Set Workspace Replacement Text",
        ActionValueType::String,
        ActionValueType::None,
        "Requires a visible workspace search panel; does not start preview or modify files.",
        "window/search",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-search-panel-replace-query",
        &[
            ActionCoverageLane::Widget,
            ActionCoverageLane::AccessibilitySmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "preview-search-panel-replacements",
        "Preview Workspace Replacements",
        ActionValueType::None,
        ActionValueType::None,
        "Requires visible workspace search results; builds the checked Replace All preview without modifying files.",
        "window/search",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-preview-search-panel-replacements",
        &[
            ActionCoverageLane::Widget,
            ActionCoverageLane::AccessibilitySmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "confirm-search-panel-replacements",
        "Confirm Workspace Replacements",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a visible Replace All preview; applies only checked preview rows through the normal safety flow.",
        "window/search",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-confirm-search-panel-replacements",
        &[
            ActionCoverageLane::Widget,
            ActionCoverageLane::AccessibilitySmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "undo-search-panel-replacements",
        "Undo Workspace Replacements",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a visible workspace search panel with an active Replace All undo backup.",
        "window/search",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-undo-search-panel-replacements",
        &[
            ActionCoverageLane::Widget,
            ActionCoverageLane::AccessibilitySmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "search-next-match",
        "Next Workspace Search Match",
        ActionValueType::None,
        ActionValueType::None,
        "Requires visible workspace search results.",
        "window/search",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-search-next-match",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "search-prev-match",
        "Previous Workspace Search Match",
        ActionValueType::None,
        ActionValueType::None,
        "Requires visible workspace search results.",
        "window/search",
        &[ActionSurface::KeyboardShortcut, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-search-prev-match",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-bookmark",
        "Toggle Bookmark",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document.",
        "window/notes",
        &[
            ActionSurface::EditorContextMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-bookmark",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "notes-toggle-bookmark",
        "Add or Remove Bookmark",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document.",
        "window/notes",
        &[ActionSurface::NotesMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-notes-toggle-bookmark",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "edit-bookmark-label",
        "Edit Bookmark",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document with a bookmark at the cursor.",
        "window/notes",
        &[
            ActionSurface::EditorContextMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-edit-bookmark-label",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "next-bookmark",
        "Next Bookmark",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document with navigable bookmarks.",
        "window/notes",
        &[
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-next-bookmark",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "prev-bookmark",
        "Previous Bookmark",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document with navigable bookmarks.",
        "window/notes",
        &[
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-prev-bookmark",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-bookmarks",
        "Browse Bookmarks",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; dialog owns empty states.",
        "window/notes",
        &[ActionSurface::CommandPalette, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-show-bookmarks",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "open-document-note",
        "Open Document Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document.",
        "window/notes",
        &[
            ActionSurface::EditorContextMenu,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-open-document-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "notes-open-document-note",
        "Open Document Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a saved active document.",
        "window/notes",
        &[ActionSurface::NotesMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-notes-open-document-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "open-folder-note",
        "Open Folder Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a current workspace folder context.",
        "window/notes",
        &[ActionSurface::CommandPalette, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-open-folder-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "notes-open-folder-note",
        "Open Folder Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a current workspace folder context.",
        "window/notes",
        &[ActionSurface::NotesMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-notes-open-folder-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-notes",
        "Browse Notes",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; browser owns empty states.",
        "window/notes",
        &[ActionSurface::CommandPalette, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-show-notes",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "notes-show-notes",
        "Browse Notes",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; browser owns empty states.",
        "window/notes",
        &[ActionSurface::NotesMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-notes-show-notes",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-notes-browser-query",
        "Set Notes Browser Query",
        ActionValueType::String,
        ActionValueType::None,
        "Requires a visible Browse Notes dialog.",
        "window/notes",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-set-notes-browser-query",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "select-notes-browser-row",
        "Select Notes Browser Row",
        ActionValueType::U32,
        ActionValueType::None,
        "Requires a visible Browse Notes dialog and a visible zero-based row index.",
        "window/notes",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-select-notes-browser-row",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "open-notes-browser-selection",
        "Open Selected Notes Browser Row",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a visible Browse Notes dialog with a selected row.",
        "window/notes",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-open-notes-browser-selection",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "discard-changes",
        "Discard Changes",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a modified file-backed active document; confirmation still applies.",
        "window/documents",
        &[ActionSurface::PrimaryMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-discard-changes",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-sidebar",
        "Toggle Sidebar",
        ActionValueType::None,
        ActionValueType::Bool,
        "Always enabled; compact layout may render the requested state differently.",
        "window/actions",
        &[
            ActionSurface::StatusBar,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-sidebar",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-sidebar-visible",
        "Set Sidebar Visibility",
        ActionValueType::Bool,
        ActionValueType::None,
        "Always enabled; compact layout may render the requested state differently.",
        "window/actions",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-set-sidebar-visible",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-properties",
        "Document Properties",
        ActionValueType::None,
        ActionValueType::Bool,
        "Always enabled; compact layout may render the requested state differently.",
        "window/actions",
        &[
            ActionSurface::HeaderButton,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-properties",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-properties-visible",
        "Set Document Properties Visibility",
        ActionValueType::Bool,
        ActionValueType::None,
        "Always enabled; compact layout may render the requested state differently.",
        "window/actions",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-set-properties-visible",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-minimap",
        "Toggle Minimap",
        ActionValueType::None,
        ActionValueType::Bool,
        "Always enabled; document and Focus Mode policy may suppress rendering.",
        "window/actions",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-minimap",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-minimap-visible",
        "Set Minimap Visibility",
        ActionValueType::Bool,
        ActionValueType::None,
        "Always enabled; document and Focus Mode policy may suppress rendering.",
        "window/actions",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-set-minimap-visible",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "fullscreen",
        "Fullscreen",
        ActionValueType::None,
        ActionValueType::None,
        "Enabled while the window is not fullscreen.",
        "window/actions",
        &[ActionSurface::PrimaryMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-fullscreen",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "unfullscreen",
        "Leave Fullscreen",
        ActionValueType::None,
        ActionValueType::None,
        "Enabled while the window is fullscreen.",
        "window/actions",
        &[ActionSurface::PrimaryMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-unfullscreen",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-fullscreen",
        "Fullscreen",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled.",
        "window/actions",
        &[
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-fullscreen",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-focus-mode",
        "Focus Mode",
        ActionValueType::None,
        ActionValueType::Bool,
        "Always enabled.",
        "window/focus_mode",
        &[
            ActionSurface::HeaderButton,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-focus-mode",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-focus-mode",
        "Set Focus Mode",
        ActionValueType::Bool,
        ActionValueType::None,
        "Always enabled; changes state through the normal Focus Mode transition.",
        "window/focus_mode",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-set-focus-mode",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-preview-pane",
        "Preview Pane",
        ActionValueType::None,
        ActionValueType::Bool,
        "Requires an active tab; exported for preview-state setup.",
        "window/preview",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::DiagnosticOnly,
        ActionExposure::Exported,
        "action-win-toggle-preview-pane",
        &[
            ActionCoverageLane::Unit,
            ActionCoverageLane::Widget,
            ActionCoverageLane::VisualSmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-preview-pane-visible",
        "Set Preview Pane Visibility",
        ActionValueType::Bool,
        ActionValueType::None,
        "Requires an active tab; exits preview-only mode before showing the side-by-side pane.",
        "window/preview",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::DiagnosticOnly,
        ActionExposure::Exported,
        "action-win-set-preview-pane-visible",
        &[
            ActionCoverageLane::Unit,
            ActionCoverageLane::Widget,
            ActionCoverageLane::VisualSmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-preview-mode",
        "Markdown Preview",
        ActionValueType::None,
        ActionValueType::Bool,
        "Requires an active tab and no visible side-by-side preview pane.",
        "window/preview",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-preview-mode",
        &[
            ActionCoverageLane::Unit,
            ActionCoverageLane::Widget,
            ActionCoverageLane::VisualSmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "set-preview-mode",
        "Set Markdown Preview Mode",
        ActionValueType::Bool,
        ActionValueType::None,
        "Requires an active tab; hides the side-by-side preview pane before entering preview-only mode.",
        "window/preview",
        &[ActionSurface::DbusAction],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-set-preview-mode",
        &[
            ActionCoverageLane::Unit,
            ActionCoverageLane::Widget,
            ActionCoverageLane::VisualSmoke,
        ],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "print",
        "Print",
        ActionValueType::None,
        ActionValueType::None,
        "Requires an active tab.",
        "window/print",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-print",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "zoom-in",
        "Zoom In",
        ActionValueType::None,
        ActionValueType::None,
        "Enabled while zoom is below the maximum.",
        "window/zoom",
        &[
            ActionSurface::CustomMenuWidget,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-zoom-in",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "zoom-out",
        "Zoom Out",
        ActionValueType::None,
        ActionValueType::None,
        "Enabled while zoom is above the minimum.",
        "window/zoom",
        &[
            ActionSurface::CustomMenuWidget,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-zoom-out",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "zoom-reset",
        "Reset Zoom",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled.",
        "window/zoom",
        &[
            ActionSurface::CustomMenuWidget,
            ActionSurface::KeyboardShortcut,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-zoom-reset",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "toggle-tab-pinned",
        "Pin or Unpin Tab",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a tab context-menu target.",
        "window/tabs",
        &[ActionSurface::TabContextMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-toggle-tab-pinned",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "close-tabs-right",
        "Close All Tabs to the Right",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a tab context-menu target; normal close safety still applies.",
        "window/tabs",
        &[ActionSurface::TabContextMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-close-tabs-right",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "close-other-tabs",
        "Close Other Tabs",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a tab context-menu target; normal close safety still applies.",
        "window/tabs",
        &[ActionSurface::TabContextMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-close-other-tabs",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "move-tab-left",
        "Move Tab Left",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a movable tab context-menu target.",
        "window/tabs",
        &[ActionSurface::TabContextMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-move-tab-left",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "move-tab-right",
        "Move Tab Right",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a movable tab context-menu target.",
        "window/tabs",
        &[ActionSurface::TabContextMenu, ActionSurface::DbusAction],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::Exported,
        "action-win-move-tab-right",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::Window,
        "show-help-overlay",
        "Keyboard Shortcuts",
        ActionValueType::None,
        ActionValueType::None,
        "Always enabled; opens the shipped keyboard-shortcuts help window.",
        "window/actions",
        &[
            ActionSurface::PrimaryMenu,
            ActionSurface::CommandPalette,
            ActionSurface::DbusAction,
        ],
        ExternalActivationSafety::StableUserCommand,
        ActionExposure::Exported,
        "action-win-show-help-overlay",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SearchOptions,
        "regex",
        "Regular Expressions",
        ActionValueType::None,
        ActionValueType::Bool,
        "Requires a visible in-document search bar.",
        "search_bar",
        &[ActionSurface::SearchOptionsMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-search-options-regex",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SearchOptions,
        "case-sensitive",
        "Case Sensitive",
        ActionValueType::None,
        ActionValueType::Bool,
        "Requires a visible in-document search bar.",
        "search_bar",
        &[ActionSurface::SearchOptionsMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-search-options-case-sensitive",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SearchOptions,
        "whole-word",
        "Match Whole Word Only",
        ActionValueType::None,
        ActionValueType::Bool,
        "Requires a visible in-document search bar.",
        "search_bar",
        &[ActionSurface::SearchOptionsMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-search-options-whole-word",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "focus-folder",
        "Focus Folder",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a directory row context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFileContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-focus-folder",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "local-history",
        "Local History",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a file row context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFileContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-local-history",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "document-note",
        "Open Document Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a file row context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFileContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-document-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "folder-note",
        "Open Folder Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a workspace folder row context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFolderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-folder-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "move-folder-up",
        "Move Up",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a movable workspace folder row context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFolderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-move-folder-up",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "move-folder-down",
        "Move Down",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a movable workspace folder row context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFolderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-move-folder-down",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "remove-folder",
        "Remove from Workspace",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a workspace folder row context and confirmation.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFolderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-remove-folder",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "new-file",
        "New File",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a file or folder context that can create children.",
        "sidebar/workspace_section",
        &[
            ActionSurface::SidebarFileContextMenu,
            ActionSurface::SidebarFolderContextMenu,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-new-file",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "new-dir",
        "New Folder",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a file or folder context that can create children.",
        "sidebar/workspace_section",
        &[
            ActionSurface::SidebarFileContextMenu,
            ActionSurface::SidebarFolderContextMenu,
        ],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-new-dir",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "rename",
        "Rename",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a renameable file or folder context.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFileContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-rename",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::SidebarSection,
        "delete",
        "Delete",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a file or folder context and confirmation.",
        "sidebar/workspace_section",
        &[ActionSurface::SidebarFileContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-section-delete",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::WorkspaceHeader,
        "add-folder",
        "Add Folder",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a workspace header context.",
        "sidebar/workspace_section",
        &[ActionSurface::WorkspaceHeaderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-ws-header-add-folder",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::WorkspaceHeader,
        "open-folder-note",
        "Open Folder Note",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a workspace header context.",
        "sidebar/workspace_section",
        &[ActionSurface::WorkspaceHeaderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-ws-header-open-folder-note",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::WorkspaceHeader,
        "rename",
        "Rename Workspace",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a workspace header context.",
        "sidebar/workspace_section",
        &[ActionSurface::WorkspaceHeaderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-ws-header-rename",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
    ActionCatalogEntry::new(
        ActionScope::WorkspaceHeader,
        "unlist",
        "Remove Workspace",
        ActionValueType::None,
        ActionValueType::None,
        "Requires a workspace header context and confirmation.",
        "sidebar/workspace_section",
        &[ActionSurface::WorkspaceHeaderContextMenu],
        ExternalActivationSafety::ContextualUserCommand,
        ActionExposure::WidgetScoped,
        "action-ws-header-unlist",
        &[ActionCoverageLane::Unit, ActionCoverageLane::Widget],
    ),
];

const STATIC_VISIBLE_ACTION_IDS: &[&str] = &[
    "win.new-tab",
    "win.open-file",
    "win.open-recent",
    "win.toggle-properties",
    "win.toggle-focus-mode",
    "win.save",
    "win.save-as",
    "win.show-local-history",
    "win.discard-changes",
    "win.print",
    "win.begin-search",
    "win.toggle-minimap",
    "win.toggle-preview-mode",
    "win.fullscreen",
    "win.unfullscreen",
    "app.preferences",
    "win.show-help-overlay",
    "app.about",
    "win.notes-show-notes",
    "win.notes-toggle-bookmark",
    "win.notes-open-document-note",
    "win.notes-open-folder-note",
    "win.toggle-sidebar",
    "win.show-line-ending-controls",
    "win.show-encoding-controls",
    "win.show-file-health",
    "win.toggle-bookmark",
    "win.edit-bookmark-label",
    "win.open-document-note",
    "search-options.regex",
    "search-options.case-sensitive",
    "search-options.whole-word",
    "win.toggle-tab-pinned",
    "win.close-tabs-right",
    "win.close-other-tabs",
    "win.move-tab-left",
    "win.move-tab-right",
    "section.focus-folder",
    "section.local-history",
    "section.document-note",
    "section.folder-note",
    "section.move-folder-up",
    "section.move-folder-down",
    "section.remove-folder",
    "section.new-file",
    "section.new-dir",
    "section.rename",
    "section.delete",
    "ws-header.add-folder",
    "ws-header.open-folder-note",
    "ws-header.rename",
    "ws-header.unlist",
];

/// Live app-action baseline from the private D-Bus inventory note.
pub const BASELINE_APP_ACTIONS: &[ObservedAction] = &[
    ObservedAction::new(
        ActionScope::App,
        "preferences",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::App,
        "quit",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::App,
        "about",
        ActionValueType::None,
        ActionValueType::None,
    ),
];

/// Live window-action baseline from the private D-Bus inventory note.
pub const BASELINE_WINDOW_ACTIONS: &[ObservedAction] = &[
    ObservedAction::new(
        ActionScope::Window,
        "show-notes",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "open-folder",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "show-help-overlay",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "close-tabs-right",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "close-tab",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "select-tab",
        ActionValueType::U32,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "save-as",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "unfullscreen",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "search-prev-match",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-bookmark",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "notes-toggle-bookmark",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "discard-changes",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "close-other-tabs",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "prev-match",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "show-encoding-controls",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-fullscreen",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "show-line-ending-controls",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "show-file-health",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "prev-bookmark",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-sidebar",
        ActionValueType::None,
        ActionValueType::Bool,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-sidebar-visible",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "move-tab-right",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "zoom-reset",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "begin-replace",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-minimap",
        ActionValueType::None,
        ActionValueType::Bool,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-minimap-visible",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-focus-mode",
        ActionValueType::None,
        ActionValueType::Bool,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-focus-mode",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "notes-open-folder-note",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "show-local-history",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "open-file",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "open-recent",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-open-popover-query",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "show-bookmarks",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "print",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-preview-mode",
        ActionValueType::None,
        ActionValueType::Bool,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-preview-mode",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "begin-search",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-search-query",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "notes-open-document-note",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "cycle-invisible-characters",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "open-folder-note",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-preview-pane",
        ActionValueType::None,
        ActionValueType::Bool,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-preview-pane-visible",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-command-palette",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-command-palette-query",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-command-palette-mode",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-properties",
        ActionValueType::None,
        ActionValueType::Bool,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-properties-visible",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-search-panel",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-search-panel-visible",
        ActionValueType::Bool,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-search-panel-query",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-search-panel-replace-query",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "preview-search-panel-replacements",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "confirm-search-panel-replacements",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "undo-search-panel-replacements",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "zoom-in",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "zoom-out",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "save",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "next-bookmark",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "fullscreen",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "toggle-tab-pinned",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "search-next-match",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "notes-show-notes",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "set-notes-browser-query",
        ActionValueType::String,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "select-notes-browser-row",
        ActionValueType::U32,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "open-notes-browser-selection",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "new-tab",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "move-tab-left",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "next-match",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "edit-bookmark-label",
        ActionValueType::None,
        ActionValueType::None,
    ),
    ObservedAction::new(
        ActionScope::Window,
        "open-document-note",
        ActionValueType::None,
        ActionValueType::None,
    ),
];
