// SPDX-License-Identifier: GPL-3.0-or-later

//! Property tests for Replace All undo over tiny deterministic files.
//!
//! The generated fixture touches the production apply and undo services, but it
//! stays bounded to a few tempdir-backed UTF-8 files with one non-overlapping
//! range each so the property remains deterministic and cheap.

use std::collections::HashSet;
use std::ops::Range;
use std::path::PathBuf;
use std::sync::atomic::AtomicBool;

use lushtext_core::model::content_search::Replacement;
use lushtext_core::services::content_search::{apply_replacements, undo_replacements};
use lushtext_core::services::filesystem::{fixture, read as fs_read};
use proptest::prelude::*;
use proptest::test_runner::TestCaseError;

use crate::support;

/// Maximum number of tiny files in one generated Replace All undo fixture.
///
/// Three files is enough to exercise multi-file backup bookkeeping while
/// keeping each property case far below integration-test cost.
const MAX_REPLACE_FILES: usize = 3;
/// Maximum generated byte offset used for the single replacement range.
const MAX_RANGE_OFFSET: usize = support::MAX_TEXT_FRAGMENT_CHARS * 2;

#[derive(Debug, Clone)]
struct ReplaceUndoCase {
    files: Vec<ReplaceUndoFile>,
}

/// One generated file and its single non-overlapping replacement range.
#[derive(Debug, Clone)]
struct ReplaceUndoFile {
    lines: Vec<String>,
    line_ending: &'static str,
    trailing_newline: bool,
    line_index: usize,
    match_range: Range<usize>,
    replacement: String,
}

impl ReplaceUndoFile {
    /// Rebuild the original file text from the generated line fixture.
    fn original_text(&self) -> String {
        let mut text = self.lines.join(self.line_ending);
        if self.trailing_newline {
            text.push_str(self.line_ending);
        }
        text
    }

    /// Build the preview instruction consumed by the production Replace All service.
    fn replacement_for_path(&self, path: PathBuf) -> Replacement {
        Replacement {
            path,
            line_number: u64::try_from(self.line_index + 1).unwrap_or(u64::MAX),
            original_line: self.lines[self.line_index].clone(),
            replaced_line: String::new(),
            replacement: self.replacement.clone(),
            match_range: self.match_range.clone(),
        }
    }
}

proptest! {
    #![proptest_config(support::property_config())]

    #[test]
    fn replace_all_then_immediate_undo_restores_original_bytes(case in replace_undo_case()) {
        let tempdir = tempfile::tempdir()
            .map_err(|error| TestCaseError::fail(format!("tempdir creation failed: {error}")))?;
        let mut originals = Vec::with_capacity(case.files.len());
        let mut replacements = Vec::with_capacity(case.files.len());
        for (index, file) in case.files.iter().enumerate() {
            let path = tempdir.path().join(format!("replace-target-{index}.txt"));
            let original_bytes = file.original_text().into_bytes();
            fixture::write_bytes(&path, &original_bytes);

            replacements.push(file.replacement_for_path(path.clone()));
            originals.push((path, original_bytes));
        }

        let expected_files = originals.len();
        let cancel = AtomicBool::new(false);
        let (result, backup) = apply_replacements(&replacements, &HashSet::new(), &cancel, None)
            .map_err(|error| TestCaseError::fail(format!("replace failed: {error}")))?;

        prop_assert_eq!(result.files_affected, expected_files);
        prop_assert_eq!(result.replaced_count, expected_files);
        prop_assert!(result.skipped_paths.is_empty());
        prop_assert!(result.errors.is_empty());
        prop_assert_eq!(backup.len(), expected_files);

        let outcome = undo_replacements(&backup);

        prop_assert_eq!(outcome.restored_count(), expected_files);
        prop_assert!(outcome.skipped_paths.is_empty());
        prop_assert!(outcome.failed_paths.is_empty());
        prop_assert!(outcome.remaining_backup.is_empty());

        for (path, original_bytes) in originals {
            let restored_bytes = fs_read::bytes(&path)
                .map_err(|error| TestCaseError::fail(format!("restore read failed: {error}")))?;
            prop_assert_eq!(restored_bytes, original_bytes);
        }
    }
}

/// Generate a tiny multi-file Replace All fixture with one valid range per file.
fn replace_undo_case() -> impl Strategy<Value = ReplaceUndoCase> {
    prop::collection::vec(replace_undo_file(), 1..=MAX_REPLACE_FILES)
        .prop_map(|files| ReplaceUndoCase { files })
}

/// Generate one tiny file fixture with one valid range.
fn replace_undo_file() -> impl Strategy<Value = ReplaceUndoFile> {
    (
        prop::collection::vec(support::text_fragment(), 1..=support::MAX_VECTOR_LEN),
        any::<bool>(),
        any::<bool>(),
        0usize..=support::MAX_VECTOR_LEN * 2,
        range_input(),
        support::optional_text_fragment(),
    )
        .prop_map(
            |(lines, use_crlf, trailing_newline, raw_line_index, match_range, replacement)| {
                let line_index = raw_line_index % lines.len();
                ReplaceUndoFile {
                    lines,
                    line_ending: if use_crlf { "\r\n" } else { "\n" },
                    trailing_newline,
                    line_index,
                    match_range,
                    replacement,
                }
            },
        )
}

/// Generate a bounded byte range with ordered endpoints.
fn range_input() -> impl Strategy<Value = Range<usize>> {
    (0usize..=MAX_RANGE_OFFSET, 0usize..=MAX_RANGE_OFFSET)
        .prop_map(|(start, end)| start.min(end)..start.max(end))
}
