// SPDX-License-Identifier: GPL-3.0-or-later

//! Property tests for deterministic Replace All text transformation.
//!
//! The property target calls the same pure helper used by the on-disk command
//! path, but it avoids files, locks, and undo persistence so generated cases
//! remain fast and reproducible.

use std::collections::BTreeSet;
use std::ops::Range;
use std::path::PathBuf;

use lushtext_core::model::content_search::Replacement;
use lushtext_core::services::content_search::apply_replacements_to_text_for_property_test;
use proptest::prelude::*;

use crate::support;

/// Maximum generated byte offset used for line replacement ranges.
const MAX_RANGE_OFFSET: usize = support::MAX_TEXT_FRAGMENT_CHARS * 2;

proptest! {
    #![proptest_config(support::property_config())]

    #[test]
    fn replacements_clip_ranges_and_apply_from_later_positions_first(
        lines in prop::collection::vec(support::text_fragment(), 1..=support::MAX_VECTOR_LEN),
        raw_replacements in prop::collection::vec(replacement_input(), 0..=support::MAX_VECTOR_LEN),
        use_crlf in any::<bool>(),
        trailing_newline in any::<bool>(),
    ) {
        let line_ending = if use_crlf { "\r\n" } else { "\n" };
        let mut original_text = lines.join(line_ending);
        if trailing_newline {
            original_text.push_str(line_ending);
        }
        let replacements = build_unique_line_replacements(&lines, raw_replacements);
        let expected = expected_replaced_text(&lines, line_ending, trailing_newline, &replacements);

        let actual = apply_replacements_to_text_for_property_test(&original_text, &replacements);

        prop_assert_eq!(actual, expected);
    }
}

/// Generate one raw replacement tuple before binding it to the generated text.
fn replacement_input() -> impl Strategy<Value = (usize, Range<usize>, String)> {
    (
        0usize..=support::MAX_VECTOR_LEN + 2,
        range_input(),
        support::optional_text_fragment(),
    )
}

/// Generate a bounded byte range with ordered endpoints.
fn range_input() -> impl Strategy<Value = Range<usize>> {
    (0usize..=MAX_RANGE_OFFSET, 0usize..=MAX_RANGE_OFFSET)
        .prop_map(|(start, end)| start.min(end)..start.max(end))
}

/// Bind generated replacements to line snapshots, keeping at most one per line.
fn build_unique_line_replacements(
    lines: &[String],
    raw_replacements: Vec<(usize, Range<usize>, String)>,
) -> Vec<Replacement> {
    let mut seen_lines = BTreeSet::new();
    let mut replacements = Vec::new();

    for (line_index, match_range, replacement) in raw_replacements {
        let line_number = u64::try_from(line_index + 1).unwrap_or(u64::MAX);
        if !seen_lines.insert(line_number) {
            continue;
        }
        let original_line = lines
            .get(line_index)
            .cloned()
            .unwrap_or_else(|| "missing generated line".to_string());
        replacements.push(Replacement {
            path: PathBuf::from("/tmp/lushtext-property-search.txt"),
            line_number,
            original_line,
            replaced_line: String::new(),
            replacement,
            match_range,
        });
    }

    replacements
}

/// Independently model the expected text transformation for generated cases.
fn expected_replaced_text(
    lines: &[String],
    line_ending: &str,
    trailing_newline: bool,
    replacements: &[Replacement],
) -> Option<(String, usize)> {
    let mut sorted = replacements.to_vec();
    sorted.sort_by(|a, b| {
        b.line_number
            .cmp(&a.line_number)
            .then(b.match_range.start.cmp(&a.match_range.start))
    });

    let mut expected_lines = lines.to_vec();
    let mut replacement_count = 0usize;
    for replacement in &sorted {
        let Ok(line_idx) = usize::try_from(replacement.line_number.saturating_sub(1)) else {
            continue;
        };
        let line = expected_lines.get_mut(line_idx)?;
        let start = replacement.match_range.start.min(line.len());
        let end = replacement.match_range.end.min(line.len());
        if start <= end {
            line.replace_range(start..end, &replacement.replacement);
            replacement_count += 1;
        }
    }

    if replacement_count == 0 {
        return None;
    }

    let mut content = expected_lines.join(line_ending);
    if trailing_newline {
        content.push_str(line_ending);
    }
    Some((content, replacement_count))
}
