// SPDX-License-Identifier: GPL-3.0-or-later

//! Property tests for deterministic Replace All text transformation.
//!
//! The property target calls the same pure helper used by the on-disk command
//! path, but it avoids files, locks, and undo persistence so generated cases
//! remain fast and reproducible.

use std::collections::BTreeSet;
use std::ops::Range;
use std::path::PathBuf;

use lushtext_core::model::content_search::{
    ContentSearchOptions, Replacement, SearchMatch, SearchMatchId, generate_replacement_preview,
};
use lushtext_core::services::content_search::{
    apply_replacements_to_text_for_property_test,
    apply_replacements_to_text_reference_for_property_test,
};
use proptest::prelude::*;

use crate::support;

/// Maximum generated byte offset used for line replacement ranges.
const MAX_RANGE_OFFSET: usize = support::MAX_TEXT_FRAGMENT_CHARS * 2;

proptest! {
    #![proptest_config(support::property_config())]

    #[test]
    fn replacements_clip_ranges_and_apply_from_later_positions_first(
        lines in prop::collection::vec(support::text_fragment(), 1..=support::MAX_VECTOR_LEN),
        raw_replacements in prop::collection::vec(replacement_input(), 0..=support::MAX_VECTOR_LEN),
        use_crlf in any::<bool>(),
        trailing_newline in any::<bool>(),
    ) {
        let line_ending = if use_crlf { "\r\n" } else { "\n" };
        let mut original_text = lines.join(line_ending);
        if trailing_newline {
            original_text.push_str(line_ending);
        }
        let replacements = build_unique_line_replacements(&lines, raw_replacements);
        let expected = expected_replaced_text(&lines, line_ending, trailing_newline, &replacements);

        let actual = apply_replacements_to_text_for_property_test(&original_text, &replacements);
        let reference = apply_replacements_to_text_reference_for_property_test(
            &original_text,
            &replacements,
        );

        prop_assert_eq!(&actual, &reference);
        prop_assert_eq!(actual, expected);
    }

    #[test]
    fn accepted_literal_preview_applies_like_direct_safe_range_replacement(
        prefix in support::text_fragment(),
        matched in "[a-zA-Z0-9]{1,16}",
        suffix in support::text_fragment(),
        replacement in support::optional_text_fragment(),
    ) {
        let line = format!("{prefix}{matched}{suffix}");
        let range = prefix.len()..prefix.len() + matched.len();
        let search_match = SearchMatch::new(
            PathBuf::from("/tmp/lushtext-preview-property.txt"),
            1,
            &line,
            range.clone(),
        )
        .with_id(SearchMatchId::from_index(0));
        let preview = generate_replacement_preview(
            &[search_match],
            &matched,
            &replacement,
            &ContentSearchOptions::default(),
        );
        let mut expected = line.clone();
        expected.replace_range(range, &replacement);

        prop_assert_eq!(preview.len(), 1);
        prop_assert_eq!(preview[0].replaced_line.as_str(), expected.as_str());
        prop_assert_eq!(
            apply_replacements_to_text_for_property_test(&line, &preview.replacements),
            Some((expected, 1)),
        );
    }

    #[test]
    fn accepted_regex_preview_preserves_capture_expansion_and_apply_semantics(
        first in "[a-z]{1,12}",
        second in "[a-z]{1,12}",
    ) {
        let matched = format!("{first}_{second}");
        let line = format!("prefix {matched} suffix");
        let start = "prefix ".len();
        let search_match = SearchMatch::new(
            PathBuf::from("/tmp/lushtext-regex-preview-property.txt"),
            1,
            &line,
            start..start + matched.len(),
        )
        .with_id(SearchMatchId::from_index(0));
        let preview = generate_replacement_preview(
            &[search_match],
            r"([a-z]+)_([a-z]+)",
            "$2-$1",
            &ContentSearchOptions::new(true, true, false, true, None),
        );
        let expected = format!("prefix {second}-{first} suffix");

        prop_assert_eq!(preview.len(), 1);
        prop_assert_eq!(preview[0].replacement.as_ref(), format!("{second}-{first}"));
        prop_assert_eq!(
            apply_replacements_to_text_for_property_test(&line, &preview.replacements),
            Some((expected, 1)),
        );
    }
}

/// Generate one raw replacement tuple before binding it to the generated text.
fn replacement_input() -> impl Strategy<Value = (usize, Range<usize>, String)> {
    (
        0usize..=support::MAX_VECTOR_LEN + 2,
        range_input(),
        support::optional_text_fragment(),
    )
}

/// Generate a bounded byte range with ordered endpoints.
fn range_input() -> impl Strategy<Value = Range<usize>> {
    (0usize..=MAX_RANGE_OFFSET, 0usize..=MAX_RANGE_OFFSET)
        .prop_map(|(start, end)| start.min(end)..start.max(end))
}

/// Bind generated replacements to line snapshots, keeping at most one per line.
fn build_unique_line_replacements(
    lines: &[String],
    raw_replacements: Vec<(usize, Range<usize>, String)>,
) -> Vec<Replacement> {
    let mut seen_lines = BTreeSet::new();
    let mut replacements = Vec::new();

    for (line_index, match_range, replacement) in raw_replacements {
        let line_number = u64::try_from(line_index + 1).unwrap_or(u64::MAX);
        if !seen_lines.insert(line_number) {
            continue;
        }
        let original_line = lines
            .get(line_index)
            .cloned()
            .unwrap_or_else(|| "missing generated line".to_string());
        replacements.push(Replacement {
            match_id: lushtext_core::model::content_search::SearchMatchId::from_index(
                replacements.len(),
            ),
            path: PathBuf::from("/tmp/lushtext-property-search.txt"),
            line_number,
            original_line: original_line.into(),
            replaced_line: String::new(),
            replacement: replacement.into(),
            match_range,
        });
    }

    replacements
}

/// Independently model the expected text transformation for generated cases.
fn expected_replaced_text(
    lines: &[String],
    line_ending: &str,
    trailing_newline: bool,
    replacements: &[Replacement],
) -> Option<(String, usize)> {
    let mut sorted = replacements.to_vec();
    sorted.sort_by(|a, b| {
        b.line_number
            .cmp(&a.line_number)
            .then(b.match_range.start.cmp(&a.match_range.start))
    });

    let mut expected_lines = lines.to_vec();
    let mut replacement_count = 0usize;
    for replacement in &sorted {
        let Ok(line_idx) = usize::try_from(replacement.line_number.saturating_sub(1)) else {
            continue;
        };
        let line = expected_lines.get_mut(line_idx)?;
        let start = replacement.match_range.start.min(line.len());
        let end = replacement.match_range.end.min(line.len());
        if start <= end {
            line.replace_range(start..end, &replacement.replacement);
            replacement_count += 1;
        }
    }

    if replacement_count == 0 {
        return None;
    }

    let mut content = expected_lines.join(line_ending);
    if trailing_newline {
        content.push_str(line_ending);
    }
    Some((content, replacement_count))
}
