// SPDX-License-Identifier: GPL-3.0-or-later

//! Feature-gated fuzz and corpus-replay harnesses for deterministic app logic.
//!
//! This module intentionally lives at the crate root because it coordinates
//! model, service, and Markdown-preview helper surfaces for external fuzz
//! targets. It is compiled only with `lushtext-core/fuzzing`, so ordinary app
//! builds do not expose these harness APIs.

use std::borrow::Cow;
use std::ops::Range;
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

use crate::model::content_search::{
    ContentSearchOptions, SearchMatch, generate_replacement_preview,
};
use crate::model::draft::{DraftEntry, DraftManifest};
use crate::model::encoding::{DocumentEncoding, LineEnding};
use crate::model::formatting_overrides::FormattingOverrides;
use crate::model::session::{SessionData, SessionTab};
use crate::services::editor_io::{apply_save_formatting_overrides, classify_bytes_for_fuzzing};
use crate::services::markdown_render::plan_markdown_cancellable;
use crate::ui::markdown_preview::{lowered_markdown_for_fuzzing, preprocess_markdown_for_fuzzing};

/// Maximum raw bytes one byte-ingestion or Markdown fuzz case processes.
///
/// Four KiB is large enough to mix encodings, Markdown constructs, and awkward
/// line endings while keeping local smoke runs predictable.
pub const FUZZ_MAX_INPUT_LEN: usize = 4096;
/// Maximum raw bytes one Markdown fuzz case processes.
///
/// The Markdown lane also plans the parsed document, and two planner ceilings
/// are only reachable from a larger input than byte ingestion needs: a fenced
/// body must pass 64 KiB to cross the carried code-text ceiling, and a table
/// must pass 1,000 cells to cross the carried cell ceiling. This bound admits
/// committed seeds for both. Coverage-guided generation stays bounded by the
/// smoke lane's own `-max_len`, which is far smaller.
pub const MARKDOWN_FUZZ_MAX_INPUT_LEN: usize = 128 * 1024;
/// Maximum raw bytes decoded into one operation script.
///
/// Operation scripts perform several helper calls per input, so they share the
/// byte-ingestion cap instead of allowing very large generated workflows.
pub const OPERATION_SCRIPT_MAX_INPUT_LEN: usize = FUZZ_MAX_INPUT_LEN;
/// Maximum operations executed by one structured operation script.
///
/// Thirty-two operations covers ordering effects without turning smoke runs into
/// random end-to-end stress tests.
pub const OPERATION_SCRIPT_MAX_OPERATIONS: usize = 32;
/// Maximum bytes used for any generated text fragment in one operation.
///
/// Keeping text fragments small makes failing seeds readable and limits parser
/// work in Markdown and replacement-preview operations.
pub const OPERATION_SCRIPT_MAX_TEXT_BYTES: usize = 256;
/// Maximum bytes used for any generated path suffix.
///
/// Synthetic paths are only model data in this harness, so long filesystem-like
/// names add noise without increasing coverage value.
pub const OPERATION_SCRIPT_MAX_PATH_BYTES: usize = 64;
/// Maximum synthetic files or persisted entries generated by one operation.
///
/// The initial operation script does not write files, but the same cap bounds
/// session and draft shapes and leaves a clear ceiling for future tiny tempdir
/// operations.
pub const OPERATION_SCRIPT_MAX_FILES: usize = 3;

/// Summary returned after exercising editor byte ingestion for one fuzz input.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct EditorBytesFuzzReport {
    /// Number of decode variants exercised for the input.
    pub decode_runs: usize,
    /// Total decoded text length observed across all decode variants.
    pub decoded_bytes: usize,
    /// Number of file-health findings surfaced across all decode variants.
    pub file_health_findings: usize,
}

/// Summary returned after exercising Markdown preprocessing and planning.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct MarkdownFuzzReport {
    /// Number of pulldown-cmark parser events produced for the input.
    pub parser_event_count: usize,
    /// Byte length of the parser input after optional inline-footnote lowering.
    pub parser_input_len: usize,
    /// Whether inline-footnote lowering changed the parser input.
    pub lowered_inline_footnotes: bool,
    /// Projection batches the GTK-free planner emitted for the input.
    pub plan_batches: usize,
    /// Units the planner replaced with an omission marker.
    pub plan_omissions: usize,
    /// Whether a global planning budget stopped before the end of the input.
    pub plan_limited: bool,
}

/// Summary returned after executing one structured operation script.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct OperationScriptReport {
    /// Number of bounded operations executed from the decoded script.
    pub operations_run: usize,
    /// Number of editor byte decode operations executed.
    pub decode_runs: usize,
    /// Number of save-formatting operations executed.
    pub formatting_runs: usize,
    /// Number of Markdown preprocessing operations executed.
    pub markdown_runs: usize,
    /// Number of replacement preview instructions generated.
    pub replacement_previews: usize,
    /// Number of session JSON round trips executed.
    pub session_roundtrips: usize,
    /// Number of draft JSON round trips executed.
    pub draft_roundtrips: usize,
    /// Number of raw session JSON decode attempts executed.
    pub session_raw_decodes: usize,
    /// Number of raw draft manifest JSON decode attempts executed.
    pub draft_raw_decodes: usize,
    /// Largest generated text fragment observed while running the script.
    pub max_text_len_seen: usize,
}

/// Exercise editor byte decoding and health classification for fuzzing/replay.
#[must_use]
pub fn exercise_editor_bytes_for_fuzzing(data: &[u8]) -> EditorBytesFuzzReport {
    let bytes = bounded_input(data);
    let mut report = EditorBytesFuzzReport::default();

    exercise_one_decode(bytes, None, &mut report);
    for encoding in DocumentEncoding::COMMON {
        exercise_one_decode(bytes, Some(encoding), &mut report);
    }

    report
}

/// Exercise Markdown preprocessing, parser setup, and GTK-free planning.
///
/// Planning is driven through the cancellable entry point the preview's own
/// worker uses, with a token that is never set, so the fuzz lane covers the same
/// checkpoint, sub-slicing, omission, and carried-embed arithmetic the app runs
/// while staying deterministic and panic-free.
///
/// # Panics
///
/// Panics only if the planner reports cancellation for a token that was never
/// set, which would violate its contract.
#[must_use]
pub fn exercise_markdown_for_fuzzing(data: &[u8]) -> MarkdownFuzzReport {
    let bytes = &data[..data.len().min(MARKDOWN_FUZZ_MAX_INPUT_LEN)];
    // Markdown preprocessing is intentionally text-level coverage. Raw invalid
    // UTF-8 behavior belongs to `exercise_editor_bytes_for_fuzzing`; this lane
    // checks what happens after the editor has produced lossy display text.
    let markdown = String::from_utf8_lossy(bytes);
    let result = preprocess_markdown_for_fuzzing(&markdown);

    // Plan the lowered text the preview actually plans, so inline-footnote
    // lowering and planning are fuzzed as the one pipeline they form in the app.
    let lowered = lowered_markdown_for_fuzzing(&markdown);
    let plan_input = lowered.as_deref().unwrap_or(&markdown);
    let cancel = AtomicBool::new(false);
    let plan = plan_markdown_cancellable(plan_input, &cancel)
        .expect("planning without a set cancellation token cannot cancel");

    MarkdownFuzzReport {
        parser_event_count: result.parser_event_count,
        parser_input_len: result.parser_input_len,
        lowered_inline_footnotes: result.lowered_inline_footnotes,
        plan_batches: plan.batches.len(),
        plan_omissions: plan.omissions(),
        plan_limited: plan.limit.is_some(),
    }
}

/// Execute a deterministic structured operation script decoded from arbitrary bytes.
#[must_use]
pub fn exercise_operation_script_for_fuzzing(data: &[u8]) -> OperationScriptReport {
    let input = &data[..data.len().min(OPERATION_SCRIPT_MAX_INPUT_LEN)];
    let mut reader = ScriptReader::new(input);
    let operation_count = 1 + reader.take_usize(OPERATION_SCRIPT_MAX_OPERATIONS);
    let mut report = OperationScriptReport::default();

    for _ in 0..operation_count {
        report.operations_run += 1;
        match reader.take_byte() % 8 {
            0 => run_formatting_operation(&mut reader, &mut report),
            1 => run_decode_operation(&mut reader, &mut report),
            2 => run_markdown_operation(&mut reader, &mut report),
            3 => run_replacement_operation(&mut reader, &mut report),
            4 => run_session_operation(&mut reader, &mut report),
            5 => run_draft_operation(&mut reader, &mut report),
            6 => run_session_raw_decode_operation(&mut reader, &mut report),
            _ => run_draft_raw_decode_operation(&mut reader, &mut report),
        }
    }

    report
}

/// Trim raw fuzzer input to the shared byte-ingestion cap.
fn bounded_input(data: &[u8]) -> &[u8] {
    &data[..data.len().min(FUZZ_MAX_INPUT_LEN)]
}

/// Drive one concrete editor decode variant and record the observable summary.
fn exercise_one_decode(
    bytes: &[u8],
    reopen_as: Option<DocumentEncoding>,
    report: &mut EditorBytesFuzzReport,
) {
    let decoded = classify_bytes_for_fuzzing(bytes, reopen_as);

    report.decode_runs += 1;
    report.decoded_bytes = report.decoded_bytes.saturating_add(decoded.content.len());
    report.file_health_findings = report
        .file_health_findings
        .saturating_add(decoded.file_health.len());

    let _ = decoded.encoding_state.summary();
    let _ = decoded.has_bom;
    for finding in decoded.file_health {
        let _ = finding.kind;
        let _ = finding.severity;
        let _ = finding.title.len();
        let _ = finding.body.len();
    }
}

/// Cursor over fuzzer input that wraps deterministically when the script needs more bytes.
struct ScriptReader<'a> {
    input: &'a [u8],
    cursor: usize,
}

impl<'a> ScriptReader<'a> {
    /// Create a reader for one bounded operation script.
    fn new(input: &'a [u8]) -> Self {
        Self { input, cursor: 0 }
    }

    /// Return one byte, using zero for empty inputs and wrapping for short seeds.
    fn take_byte(&mut self) -> u8 {
        if self.input.is_empty() {
            return 0;
        }
        let byte = self.input[self.cursor % self.input.len()];
        self.cursor = self.cursor.wrapping_add(1);
        byte
    }

    /// Return a small integer in `0..=max` without depending on platform pointer width.
    fn take_usize(&mut self, max: usize) -> usize {
        if max == 0 {
            return 0;
        }
        usize::from(self.take_byte()) % (max + 1)
    }

    /// Return a generated byte fragment with a deterministic length cap.
    fn take_bytes(&mut self, max_len: usize) -> Cow<'static, [u8]> {
        let len = self.take_usize(max_len);
        let mut bytes = Vec::with_capacity(len);
        for _ in 0..len {
            bytes.push(self.take_byte());
        }
        Cow::Owned(bytes)
    }

    /// Return a generated lossy-UTF-8 text fragment.
    fn take_text(&mut self) -> String {
        String::from_utf8_lossy(&self.take_bytes(OPERATION_SCRIPT_MAX_TEXT_BYTES)).into_owned()
    }

    /// Return a stable synthetic path that never points into the real user home.
    fn take_path(&mut self) -> PathBuf {
        let raw = self.take_bytes(OPERATION_SCRIPT_MAX_PATH_BYTES);
        let mut suffix = String::new();
        for byte in raw.iter().take(OPERATION_SCRIPT_MAX_PATH_BYTES) {
            let rendered = match byte {
                b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'-' | b'_' | b'.' => char::from(*byte),
                _ => '_',
            };
            suffix.push(rendered);
        }
        if suffix.is_empty() {
            suffix.push_str("seed");
        }
        Path::new("/workspace/operation-fuzz").join(suffix)
    }
}

/// Exercise save-formatting idempotence over one generated text fragment.
fn run_formatting_operation(reader: &mut ScriptReader<'_>, report: &mut OperationScriptReport) {
    let text = reader.take_text();
    let overrides = FormattingOverrides {
        tab_width: Some(u32::from(reader.take_byte() % 12) + 1),
        insert_spaces: Some(reader.take_byte() & 1 == 1),
        indent_width: Some(match reader.take_byte() % 13 {
            0 => -1,
            value => i32::from(value),
        }),
        line_ending: Some(line_ending_from_byte(reader.take_byte())),
        save_encoding: Some(encoding_from_byte(reader.take_byte())),
        trim_trailing_whitespace: Some(reader.take_byte() & 1 == 1),
        insert_final_newline: Some(reader.take_byte() & 1 == 1),
    };

    let once = apply_save_formatting_overrides(&text, overrides);
    let twice = apply_save_formatting_overrides(&once, overrides);
    assert_eq!(twice, once, "save-formatting operation must be idempotent");

    report.formatting_runs += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(text.len()).max(once.len());
}

/// Exercise editor byte decode/redecode over one generated byte fragment.
fn run_decode_operation(reader: &mut ScriptReader<'_>, report: &mut OperationScriptReport) {
    let bytes = reader.take_bytes(OPERATION_SCRIPT_MAX_TEXT_BYTES);
    let reopen_as = if reader.take_byte() & 1 == 1 {
        Some(encoding_from_byte(reader.take_byte()))
    } else {
        None
    };
    let decoded = classify_bytes_for_fuzzing(&bytes, reopen_as);

    report.decode_runs += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(decoded.content.len());
    let _ = decoded.encoding_state.summary();
    let _ = decoded.has_bom;
    let _ = decoded.file_health.len();
}

/// Exercise Markdown preprocessing and parser setup over one generated text fragment.
fn run_markdown_operation(reader: &mut ScriptReader<'_>, report: &mut OperationScriptReport) {
    let markdown = reader.take_text();
    let result = preprocess_markdown_for_fuzzing(&markdown);

    report.markdown_runs += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(markdown.len());
    let _ = result.parser_event_count;
    let _ = result.parser_input_len;
    let _ = result.lowered_inline_footnotes;
}

/// Exercise replacement preview generation over one generated line and range.
fn run_replacement_operation(reader: &mut ScriptReader<'_>, report: &mut OperationScriptReport) {
    let mut line = reader.take_text();
    if line.is_empty() {
        line.push('x');
    }
    let range = generated_char_boundary_range(&line, reader);
    let replacement = reader.take_text();
    let matches = [SearchMatch::new(
        reader.take_path(),
        u64::from(reader.take_byte()) + 1,
        &line,
        range,
    )];
    let options = ContentSearchOptions::default();
    let previews = generate_replacement_preview(&matches, "", &replacement, &options);

    report.replacement_previews = report.replacement_previews.saturating_add(previews.len());
    report.max_text_len_seen = report
        .max_text_len_seen
        .max(line.len())
        .max(replacement.len());
}

/// Exercise session JSON round trips over bounded generated model data.
fn run_session_operation(reader: &mut ScriptReader<'_>, report: &mut OperationScriptReport) {
    let tab_count = reader.take_usize(OPERATION_SCRIPT_MAX_FILES);
    let mut tabs = Vec::with_capacity(tab_count);
    for _ in 0..tab_count {
        tabs.push(SessionTab {
            path: if reader.take_byte() & 1 == 1 {
                Some(reader.take_path())
            } else {
                None
            },
            draft_id: if reader.take_byte() & 1 == 1 {
                Some(format!("draft-{:03}", reader.take_byte()))
            } else {
                None
            },
            cursor_line: u32::from(reader.take_byte()),
            cursor_col: u32::from(reader.take_byte()),
            scroll_line: u32::from(reader.take_byte()),
            pinned: reader.take_byte() & 1 == 1,
        });
    }
    let session = SessionData {
        tabs,
        active_tab_index: if reader.take_byte() & 1 == 1 {
            Some(reader.take_usize(OPERATION_SCRIPT_MAX_FILES + 1))
        } else {
            None
        },
    };
    let json = serde_json::to_string(&session).expect("session operation must serialize");
    let decoded: SessionData =
        serde_json::from_str(&json).expect("session operation must deserialize");

    report.session_roundtrips += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(json.len());
    let _ = decoded.tabs.len();
    let _ = decoded.active_tab_index;
}

/// Exercise panic safety for corrupt or truncated session JSON bytes.
fn run_session_raw_decode_operation(
    reader: &mut ScriptReader<'_>,
    report: &mut OperationScriptReport,
) {
    let bytes = reader.take_bytes(OPERATION_SCRIPT_MAX_TEXT_BYTES);
    let decoded = serde_json::from_slice::<SessionData>(bytes.as_ref());

    report.session_raw_decodes += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(bytes.len());
    if let Ok(session) = decoded {
        let _ = session.tabs.len();
        let _ = session.active_tab_index;
    }
}

/// Exercise draft manifest JSON round trips over bounded generated model data.
fn run_draft_operation(reader: &mut ScriptReader<'_>, report: &mut OperationScriptReport) {
    let draft_count = reader.take_usize(OPERATION_SCRIPT_MAX_FILES);
    let mut drafts = Vec::with_capacity(draft_count);
    for _ in 0..draft_count {
        drafts.push(DraftEntry {
            draft_id: format!("draft-{:03}", reader.take_byte()),
            original_path: if reader.take_byte() & 1 == 1 {
                Some(reader.take_path())
            } else {
                None
            },
            original_mtime_secs: if reader.take_byte() & 1 == 1 {
                Some(u64::from(reader.take_byte()))
            } else {
                None
            },
            saved_at_secs: u64::from(reader.take_byte()),
        });
    }
    let manifest = DraftManifest {
        drafts,
        cleanup_continuation: None,
    };
    let json = serde_json::to_string(&manifest).expect("draft operation must serialize");
    let decoded: DraftManifest =
        serde_json::from_str(&json).expect("draft operation must deserialize");

    report.draft_roundtrips += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(json.len());
    let _ = decoded.drafts.len();
}

/// Exercise panic safety for corrupt or truncated draft manifest JSON bytes.
fn run_draft_raw_decode_operation(
    reader: &mut ScriptReader<'_>,
    report: &mut OperationScriptReport,
) {
    let bytes = reader.take_bytes(OPERATION_SCRIPT_MAX_TEXT_BYTES);
    let decoded = serde_json::from_slice::<DraftManifest>(bytes.as_ref());

    report.draft_raw_decodes += 1;
    report.max_text_len_seen = report.max_text_len_seen.max(bytes.len());
    if let Ok(manifest) = decoded {
        let _ = manifest.drafts.len();
    }
}

/// Pick a byte range that always lands on UTF-8 character boundaries.
fn generated_char_boundary_range(line: &str, reader: &mut ScriptReader<'_>) -> Range<usize> {
    let mut boundaries: Vec<usize> = line.char_indices().map(|(index, _)| index).collect();
    boundaries.push(line.len());
    boundaries.sort_unstable();
    boundaries.dedup();

    let start_index = reader.take_usize(boundaries.len().saturating_sub(1));
    let end_index = reader.take_usize(boundaries.len().saturating_sub(1));
    let start = boundaries[start_index.min(end_index)];
    let end = boundaries[start_index.max(end_index)];
    start..end
}

/// Decode a generated byte into one supported document encoding.
fn encoding_from_byte(byte: u8) -> DocumentEncoding {
    DocumentEncoding::COMMON[usize::from(byte) % DocumentEncoding::COMMON.len()]
}

/// Decode a generated byte into one line-ending policy.
fn line_ending_from_byte(byte: u8) -> LineEnding {
    match byte % 4 {
        0 => LineEnding::Lf,
        1 => LineEnding::Crlf,
        2 => LineEnding::Cr,
        _ => LineEnding::Mixed,
    }
}
