#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$script_dir/.." && pwd)"
tmpdir="$(mktemp -d)"
fixture="$tmpdir/repo"
bin_dir="$tmpdir/bin"

cleanup() {
    rm -rf "$tmpdir"
}
trap cleanup EXIT

assert_eq() {
    local label="$1"
    local expected="$2"
    local actual="$3"

    if [[ "$expected" != "$actual" ]]; then
        printf 'FAIL: %s\n  expected: %s\n  actual:   %s\n' "$label" "$expected" "$actual" >&2
        exit 1
    fi
}

assert_success() {
    local label="$1"
    shift

    if ! "$@" > "$tmpdir/assert-success.log" 2>&1; then
        printf 'FAIL: %s\n' "$label" >&2
        cat "$tmpdir/assert-success.log" >&2
        exit 1
    fi
}

assert_failure() {
    local label="$1"
    shift

    if "$@" > "$tmpdir/assert-failure.log" 2>&1; then
        printf 'FAIL: %s succeeded unexpectedly\n' "$label" >&2
        exit 1
    fi
}

write_fixture_files() {
    mkdir -p \
        "$fixture/crates/lushtext" \
        "$fixture/crates/lushtext-core" \
        "$fixture/data" \
        "$fixture/build-aux"

    cat > "$fixture/meson.build" <<'EOF'
project('lushtext',
  version: '0.1.0',
  meson_version: '>= 0.62.0',
  license: 'GPL-3.0-or-later',
)
EOF

    cat > "$fixture/crates/lushtext/Cargo.toml" <<'EOF'
[package]
name = "lushtext"
version = "0.1.0"
edition = "2024"
EOF

    cat > "$fixture/crates/lushtext-core/Cargo.toml" <<'EOF'
[package]
name = "lushtext-core"
version = "0.1.0"
edition = "2024"
EOF

    cat > "$fixture/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "lushtext"
version = "0.1.0"

[[package]]
name = "lushtext-core"
version = "0.1.0"
EOF

    cat > "$fixture/data/dev.cominotti.lushtext.metainfo.xml.in" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>dev.cominotti.lushtext</id>
  <releases>
    <release version="0.1.0" date="2026-04-02">
      <description>
        <p>Initial release.</p>
      </description>
    </release>
  </releases>
</component>
EOF

    cat > "$fixture/data/dev.cominotti.lushtext.desktop.in" <<'EOF'
[Desktop Entry]
Name=LushText
Exec=lushtext %U
Icon=dev.cominotti.lushtext
Terminal=false
Type=Application
Categories=TextEditor;Utility;GTK;GNOME;
MimeType=text/plain;
EOF

    cat > "$fixture/build-aux/cargo-sources.json" <<'EOF'
[]
EOF

    cat > "$fixture/build-aux/dev.cominotti.lushtext.Flatpak.json" <<'EOF'
{
  "id": "dev.cominotti.lushtext",
  "runtime": "org.gnome.Platform",
  "runtime-version": "50",
  "sdk": "org.gnome.Sdk",
  "sdk-extensions": ["org.freedesktop.Sdk.Extension.rust-stable"],
  "command": "lushtext",
  "finish-args": ["--socket=wayland"],
  "build-options": {
    "append-path": "/usr/lib/sdk/rust-stable/bin",
    "env": {
      "CARGO_HOME": "/run/build/lushtext/cargo"
    }
  },
  "cleanup": ["*.a"],
  "modules": [
    {
      "name": "lushtext",
      "buildsystem": "meson",
      "config-opts": ["-Dprofile=release"],
      "sources": [
        {
          "type": "dir",
          "path": ".."
        },
        "cargo-sources.json"
      ]
    }
  ]
}
EOF

    cat > "$fixture/notes.txt" <<'EOF'
Release notes & polish
Second paragraph
EOF
}

write_stub_tools() {
    mkdir -p "$bin_dir"

    cat > "$bin_dir/cargo" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [[ "$1" == "update" && "${2:-}" == "-w" ]]; then
    lushtext_version="$(awk -F\" '/^version = "/ { print $2; exit }' crates/lushtext/Cargo.toml)"
    core_version="$(awk -F\" '/^version = "/ { print $2; exit }' crates/lushtext-core/Cargo.toml)"
    awk -v lush="$lushtext_version" -v core="$core_version" '
        $0 == "name = \"lushtext\"" {
            print
            getline
            print "version = \"" lush "\""
            next
        }
        $0 == "name = \"lushtext-core\"" {
            print
            getline
            print "version = \"" core "\""
            next
        }
        { print }
    ' Cargo.lock > Cargo.lock.tmp
    mv Cargo.lock.tmp Cargo.lock
    exit 0
fi

echo "unexpected cargo invocation: $*" >&2
exit 1
EOF

    cat > "$bin_dir/flatpak-cargo-generator" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

output=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -o)
            output="$2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done
[[ -n "$output" ]] || { echo "missing -o" >&2; exit 1; }
printf '[]\n' > "$output"
EOF

    cat > "$bin_dir/appstreamcli" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF

    cat > "$bin_dir/desktop-file-validate" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
[[ "$1" == *.desktop ]] || exit 1
grep -q '^\[Desktop Entry\]' "$1"
EOF

    cat > "$bin_dir/flatpak" <<'EOF'
#!/usr/bin/env bash
exit 1
EOF

    cat > "$bin_dir/flatpak-builder" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" > "$FLATPAK_BUILDER_LOG"
exit 0
EOF

    chmod +x "$bin_dir"/*
}

with_release_lib() {
    local code="$1"

    PATH="$bin_dir:$PATH" \
    FLATPAK_BUILDER_LOG="$tmpdir/flatpak-builder.log" \
    LUSHTEXT_RELEASE_REPO_ROOT="$fixture" \
    LUSHTEXT_RELEASE_LIB_ONLY=1 \
        bash -c 'source "$1"; eval "$2"' bash "$repo_root/scripts/release.sh" "$code"
}

run_release_script() {
    PATH="$bin_dir:$PATH" \
    FLATPAK_BUILDER_LOG="$tmpdir/flatpak-builder.log" \
    LUSHTEXT_RELEASE_REPO_ROOT="$fixture" \
        "$repo_root/scripts/release.sh" "$@"
}

write_fixture_files
write_stub_tools

git -C "$fixture" init -b main >/dev/null
git -C "$fixture" config user.email "test@example.com"
git -C "$fixture" config user.name "Test User"
git -C "$fixture" add .
git -C "$fixture" commit -m "initial" >/dev/null
git -C "$fixture" tag v1.0.0
git -C "$fixture" tag v1.1.0-alpha.1
git -C "$fixture" tag v1.1.0-alpha.2

assert_success "accepts stable semver" with_release_lib 'validate_semver v1.2.3'
assert_success "accepts prerelease semver" with_release_lib 'validate_semver v1.2.3-alpha.1'
assert_failure "rejects missing v prefix" with_release_lib 'validate_semver 1.2.3'
assert_failure "rejects incomplete semver" with_release_lib 'validate_semver v1.2'

next="$(with_release_lib 'compute_next_version patch ""; printf "%s\n" "$next_version"' | tail -1)"
assert_eq "patch bump" "v1.0.1" "$next"

next="$(with_release_lib 'compute_next_version minor alpha ""; printf "%s\n" "$next_version"' | tail -1)"
assert_eq "alpha stream bump" "v1.1.0-alpha.3" "$next"

next="$(with_release_lib 'compute_next_version minor "" 1; printf "%s\n" "$next_version"' | tail -1)"
assert_eq "promoted stable bump" "v1.1.0" "$next"

assert_failure "stable promotion guard" with_release_lib 'compute_next_version minor "" ""'
assert_failure "missing release notes fail real prep" with_release_lib 'prepare_release_files v1.2.3 "" ""'

before_status="$(git -C "$fixture" status --porcelain)"
assert_success "dry-run release does not mutate" run_release_script bump patch "" "" "" 1
cp "$tmpdir/assert-success.log" "$tmpdir/dry-run.log"
after_status="$(git -C "$fixture" status --porcelain)"
assert_eq "dry-run working tree status" "$before_status" "$after_status"
grep -q 'Would prepare Cominotti Flatpak repository publication' "$tmpdir/dry-run.log"
grep -q 'https://flatpak.cominotti.dev/repo/' "$tmpdir/dry-run.log"
grep -q 'Cloudflare Pages project cominotti-sw-flatpak' "$tmpdir/dry-run.log"
grep -q 'Cloudflare Pages preflight' "$tmpdir/dry-run.log"
grep -q 'Cloudflare R2 behind flatpak.cominotti.dev' "$tmpdir/dry-run.log"
grep -q 'Would keep Flathub handoff optional' "$tmpdir/dry-run.log"

with_release_lib 'prepare_release_files v0.1.0 notes.txt ""; validate_release_metadata v0.1.0'
grep -q '<release version="0.1.0"' "$fixture/data/dev.cominotti.lushtext.metainfo.xml.in"
grep -q 'Release notes &amp; polish' "$fixture/data/dev.cominotti.lushtext.metainfo.xml.in"
if grep -q 'Initial release\.' "$fixture/data/dev.cominotti.lushtext.metainfo.xml.in"; then
    printf 'FAIL: existing AppStream release was not replaced\n' >&2
    exit 1
fi

with_release_lib 'prepare_release_files v1.2.3 notes.txt ""; validate_release_metadata v1.2.3'
grep -q "version: '1.2.3'" "$fixture/meson.build"
grep -q 'version = "1.2.3"' "$fixture/crates/lushtext/Cargo.toml"
grep -q 'version = "1.2.3"' "$fixture/crates/lushtext-core/Cargo.toml"
grep -q '<release version="1.2.3"' "$fixture/data/dev.cominotti.lushtext.metainfo.xml.in"
grep -q 'Release notes &amp; polish' "$fixture/data/dev.cominotti.lushtext.metainfo.xml.in"
assert_success "validate-tag accepts synchronized fixture" with_release_lib 'validate_tag_release v1.2.3 1'

echo "release helper tests passed"
